---
- name: Ensure required dependencies are installed
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: true

- name: Ensure Docker keyring directory exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Add Docker's official GPG key safely with timeout
  shell: >
    timeout 30 bash -c '
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
      gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    '
  args:
    executable: /bin/bash
  register: docker_gpg
  failed_when: docker_gpg.rc != 0
  become: true

- name: Add Docker APT repository for Ubuntu 24.04 (use jammy fallback)
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    filename: docker
  become: true

- name: Install Docker Engine packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: true

- name: Ensure Docker service is enabled and started
  service:
    name: docker
    state: started
    enabled: yes
  become: true
