---
- name: Ensure keyring directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Install base tools for Docker setup
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes
  become: true

- name: Add Docker GPG key to /etc/apt/keyrings
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    filename: docker
    state: present
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install Docker Engine with recommended packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Verify Docker is working by pulling hello-world
  command: docker run hello-world
  register: docker_test
  ignore_errors: true
  become: true

- name: Fail if Docker hello-world test failed
  fail:
    msg: "❌ Docker did not run correctly on {{ inventory_hostname }}"
  when: docker_test.rc != 0
