---
- name: Install Docker via shell script
  hosts: all
  become: true
  tasks:

    - name: Copy Docker install script to remote host
      copy:
        src: docker.sh
        dest: /tmp/docker-install.sh
        mode: '0755'

    - name: Run Docker install script
      command: /tmp/docker-install.sh
